Name:           ros-indigo-turtlebot-gazebo
Version:        2.2.1
Release:        1%{?dist}
Summary:        ROS turtlebot_gazebo package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/turtlebot_gazebo
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-depthimage-to-laserscan
Requires:       ros-indigo-diagnostic-aggregator
Requires:       ros-indigo-gazebo-ros
Requires:       ros-indigo-kobuki-gazebo-plugins
Requires:       ros-indigo-robot-pose-ekf
Requires:       ros-indigo-robot-state-publisher
Requires:       ros-indigo-turtlebot-bringup
Requires:       ros-indigo-turtlebot-description
Requires:       ros-indigo-turtlebot-navigation
Requires:       ros-indigo-xacro
Requires:       ros-indigo-yocs-cmd-vel-mux
BuildRequires:  ros-indigo-catkin

%description
Gazebo launchers and worlds for TurtleBot simulation

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Wed Sep 16 2015 Marcus Liebhardt <marcus.liebhardt@yujinrobot.com> - 2.2.1-1
- Autogenerated by Bloom

* Fri Aug 07 2015 Marcus Liebhardt <marcus.liebhardt@yujinrobot.com> - 2.2.1-0
- Autogenerated by Bloom

* Tue Dec 30 2014 Marcus Liebhardt <marcus.liebhardt@yujinrobot.com> - 2.2.0-0
- Autogenerated by Bloom

